FROM ubuntu:latest

COPY README.md create-stunnel.py sugariq-redis-migrate.py /tmp/

RUN apt update && apt upgrade -y && \
    apt install -y python python-pip net-tools inetutils-ping emacs-nox stunnel \
                   lsof netcat time vim redis && \
    pip install redis

WORKDIR /tmp
ENTRYPOINT tail -f /dev/null



